### ISSUE TITLE
list index out of range when running function_extractor.py

### ISSUE THREAD

**Issue by Samfisheryu** [sdsen/opened_extraction#12] opened 2022-12-01 20:39 UTC
![image](https://user-images.githubusercontent.com/88549858/205154426-868ce646-3c42-48e1-8613-ae10c767f1f1.png)
after I successfully ran the extraction_runner.py, I got func.out as following (There is only one function because I pick connection_table_lookup which only occurs once in Katran)
![image](https://user-images.githubusercontent.com/88549858/205154547-553e1f60-5fc6-4c13-933d-f8f8e9c7b78e.png)
Then I tried to run function_extractor.py
![image](https://user-images.githubusercontent.com/88549858/205154779-cb8b4a4c-3a04-44e5-a858-c6fa87edd58c.png)
It shows error like this
![image](https://user-images.githubusercontent.com/88549858/205154893-150ef5ba-0003-4faf-a656-791e1fc0b29b.png)
Can I get a sense of what is going on with this?

**Comment by qthuang** [comment] 2022-12-01 21:22
The problem is caused by line 311 function-extractor.py. By uncommenting the print("Prossing", line), we found that the parsing does not stop when there is no line needed to be parsed. 
<img width="1172" alt="截屏2022-12-01 16 18 56" src="https://user-images.githubusercontent.com/60091633/205161814-08efe967-77a0-48ab-96a5-4fbc50b22047.png">

**Comment by qthuang** [comment] 2022-12-01 21:24
In the corresponding func.out, there is no line after  "reals,/home/ubuntu/opened/code_annotation/Katran.commented_OPENED_katran_balancer_kern.c, 199, 0"

**Comment by qthuang** [comment] 2022-12-01 21:49
Also, when extracting some functions, the func.out sometimes have the line 
#DUPLICATE MAP DEFNS
{#map_name,file_locations
}
Which also causes IndesError when parsing. 
<img width="1223" alt="截屏2022-12-01 16 47 56" src="https://user-images.githubusercontent.com/60091633/205165951-5d9daac5-c610-4327-a9b1-947b63165cbf.png">

**Comment by palanik1** [comment] 2022-12-02 06:24
@qthuang This should be fixed...please pull latest code and let us know if it works?

**Closed** 2022-12-02 16:53 UTC
